config/routes.rb
Rails.application.routes.draw do
  scope constraints: { format: :html } do

    resources :sessions, only: [:create, :destroy]
    resources :comments
    resources :links,    only: [:index, :show, :new, :create]
    resources :votes,    only: [:create]
    resources :users

    get "/submit" => "links#new"

    get '/sign_in',  to: 'users#new'
    delete '/sign_out', to: 'sessions#destroy'

    get "/:category/submit" => "links#new"
    get "/:category/:subcategory/submit" => "links#new"
    get "/:category/:subcategory/:slug" => "links#show"
    get "/:category/:subcategory" => "links#index"
    get "/:category" => "links#index"
  end
  root 'links#index'
  get '*unmatched_route', to: 'application#raise_not_found!'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, presence: true, length: { minimum: 1 }

  before_save :cache_markdown

  belongs_to :link, counter_cache: true
  belongs_to :user

  has_many :children, class_name: 'Comment',
                      foreign_key: 'comment_id'

  belongs_to :parent, class_name: 'Comment',
                      foreign_key: 'comment_id'

  before_create :set_depth
  before_create :set_link_id

  scope :for_link, -> (link_id, user_id) do
    order('comments.score, comments.created_at')
    .joins('LEFT JOIN votes on votes.comment_id=comments.id AND votes.user_id=' + user_id.to_i.to_s)
    .select(['votes.change', 'comments.*'].join(', '))
    .where(link_id: link_id)
  end

  default_scope do
    joins(:user).
      select(['users.name as user_name', 'comments.*'].join(', '))
  end

  EDIT_TIME_LIMIT = 2.hours
  DELETE_TIME_LIMIT = 2.hours

  def self.by_parent(link_id, user_id)
    by_parent = {}
    Comment.for_link(link_id, user_id).find_each do |item|
      parent_id = item[:comment_id] ? item[:comment_id] : 0
      by_parent[parent_id] ||= []
      by_parent[parent_id] << item
    end
    by_parent
  end

  def can_edit?(user)
    !user.nil? && (user.admin || (created_at < EDIT_TIME_LIMIT.ago && user.id == user_id))
  end

  def can_delete?(user)
    !user.nil? && (user.admin || (created_at < DELETE_TIME_LIMIT.ago && user.id == user_id))
  end

  def score
    score_up - score_down
  end

  private

  def set_link_id
    self.link_id = parent.link_id unless parent.nil?
  end

  def set_depth
    self.depth = parent.nil? ? 0 : parent.depth + 1
  end

  def cache_markdown
    self.text_cached = MarkdownParser.markdown_convert text
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :must_be_signed_in
  before_action :permission_to_edit, only: :update
  before_action :permission_to_delete, only: :destroy

  def create
    comment = Comment.new params.require(:comment).permit(:text, :link_id, :comment_id)
    comment.ip_address = request.remote_ip
    comment.user_id = current_user.id
    redirect = comment.link.comments_url if comment.save # verify_captcha(link) &&
  end

  def update
    @comment.update params.require(:comment).permit(:text)
    render json: json_result(@comment, text_cached: @comment.text_cached, text: @comment.text)
  end

  def destroy
    @comment.update deleted: true
    # TODO: Should reload partial instead of redirect
    redirect_to @comment.link.comments_url
  end

  private

  def permission_to_edit
    @comment = Comment.find_by! id: params[:id]
    no_permission_redirect! unless @comment.can_edit?(current_user)
  end

  def permission_to_delete
    @comment = Comment.find_by! id: params[:id]
    no_permission_redirect! unless @comment.can_delete?(current_user)
  end
end

app/views/comments/_comment.html.slim
- if !comment.deleted || @link.comments_by_parent(current_user_id)[comment.id]
  div.comment-container class='#{comment.depth % 2 == 1 ? 'even' : 'odd'}'
    section id='comment_#{comment.id}' class='comment#{comment_classes(comment)}' data-score='#{comment.score}'
      - if comment.deleted
        div.comment-header
          = t('.posted_html', user: content_tag(:em, t(:deleted)),
                              created: time_ago_in_words(comment.created_at))
        div.comment-markdown.markdown
          = t('.comment_deleted')
      - else
        div.comment-header
          = link_to '&#9650;'.html_safe, votes_path, class: 'up'
          = link_to '&#9660;'.html_safe, votes_path, class: 'down'
          span data-score-display='$1:' class='score#{signed_class(comment.score)}'
            = "%+d:" % comment.score
          = t('.posted_html', user: link_to(comment.user_name, user_path(comment.user_name.downcase)),
                              created: time_ago_in_words(comment.created_at))
          - if signed_in?
            ul.comment-options
              - if comment.can_edit?(current_user)
                li.edit = link_to fa_tag('edit') + content_tag(:span, t('buttons.edit')),
                  comment_path(comment.id), data: { content: comment.text }
              - if comment.can_delete?(current_user)
                li.delete = link_to fa_tag('remove') + content_tag(:span, t('buttons.delete')),
                  comment_path(comment.id), method: :delete, data: { confirm: t(:confirm_delete) }
              - else
                li.report = link_to fa_tag('exclamation-triangle') + content_tag(:span, t('buttons.report')), '#'
              li.reply = link_to fa_tag('reply') + content_tag(:span, t('buttons.reply')), '#'
        div.comment-markdown.markdown
          = comment.text_cached.html_safe
    - if @link.comments_by_parent(current_user_id)[comment.id]
      = render(partial: 'comments/comment', collection: @link.comments_by_parent(current_user_id)[comment.id])

app/views/comments/_markdown_help.html.slim
div.markdown-field
  = field
  small
    a href='#' onclick='return markdown_toggle(this)' = t 'markdown_help'
  = cache 'markdown_help' do
    dl.markdown-help.markdown
      dt.header Markdown
      dd.header Result
      = markdown_example '*italics* or _italics_'
      = markdown_example '**bold** or __bold__'
      = markdown_example 'strike ~~that~~ out'
      = markdown_example 'e=mc^2^'
      = markdown_example 'h~2~o'
      = markdown_example '[link text](www.google.com)'
      = markdown_example "> quoting somebody\n> another line\n>> another layer!"
      = markdown_example "* unordered list\n* another point\n"
      = markdown_example "1. ordered list\n2. another number\n  * nesting is supported\n    1. 3 levels even"