config/routes.rb
Rails.application.routes.draw do
  scope constraints: { format: :html } do

    resources :sessions, only: [:create, :destroy]
    resources :comments
    resources :links,    only: [:index, :show, :new, :create]
    resources :votes,    only: [:create]
    resources :users

    get "/submit" => "links#new"

    get '/sign_in',  to: 'users#new'
    delete '/sign_out', to: 'sessions#destroy'

    get "/:category/submit" => "links#new"
    get "/:category/:subcategory/submit" => "links#new"
    get "/:category/:subcategory/:slug" => "links#show"
    get "/:category/:subcategory" => "links#index"
    get "/:category" => "links#index"
  end
  root 'links#index'
  get '*unmatched_route', to: 'application#raise_not_found!'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true,
                   length: { in: 3..25 },
                   format: { with: /[a-z0-9\-]+/i },
                   uniqueness: { case_sensitive: false }
  validates :email, allow_blank: true,
                    length: { maximum: 255 },
                    format: { with:  /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }, if: :password_digest_changed?
  validates :ip_address, presence: true

  before_save :name_to_lower

  cattr_accessor :current

  has_many :user_auths
  has_secure_password

  def valid_token?(token)
    UserAuth.find_by user_id: id, auth_key: token
  end

  def create_token
    token = SecureRandom.urlsafe_base64(50)
    UserAuth.create user_id: id, auth_key: token
    token
  end

  def to_param
    name_lower
  end

  def profile_url
    '/users/' + name_lower
  end

  def can_edit?(user)
    !user.nil? && !user.id.nil? && (user.admin || user.id == user_id)
  end

  private

  def name_to_lower
    self.name_lower = name.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :permission_to_edit, only: [:edit, :update]
  before_action :permission_to_destroy, only: [:destroy]

  def new
  end

  def create
    user = User.new params.require(:user).permit(:name, :email, :password, :password_confirmation)
    user.ip_address = request.remote_ip
    if verify_captcha(user) && user.save
      sign_in user, remember: params[:user][:remember]
      flash[:success] = t '.success_message', user: user.name
    end
    render json: json_result(user, redirect: root_path)
  end

  def show
    @user = User.find_by! name_lower: params[:id]
    @title = @user.name
  end

  def edit
  end

  def update
    if !params[:user][:update_password].nil? # Updating password
      bf = BruteForce.within_timeout.first_or_initialize ip_address: request.remote_ip

      if bf.banned? # Banned because of brute force
        @user.errors.add :base, t('errors.locked_out', time: bf.time_left_in_words)
      elsif params[:user][:password].blank?
        # Because of quirks with has_secure_password, blank passwords aren't validated automatically
        @user.errors.add :password, :blank
      elsif !@user.authenticate(params[:user][:current_password])
        @user.errors.add :base, t('.error_current_password_mismatch')
        bf.increment!
      else
        params.require(:user).permit(:password, :password_confirmation)
        @user.update(params.require(:user).permit(:password, :password_confirmation))
      end
    else # Updating all other attributes
      @user.update user_update_params
    end

    # Note: checking user.valid? flushes custom errors, so we call it last
    if !(params[:user][:update_password].nil? && params[:user][:update_profile].nil?) && @user.errors.empty? && @user.valid?
      redirect = user_path(current_user.name_lower)
      flash[:success] = !params[:user][:update_password].nil? ? t('.password_updated') : t('.profile_updated')
    end

    render json: json_result(@user, redirect: redirect)
  end

  private

  def user_update_params
    params.require(:user).permit(:email, :profile, :show_nsfw)
  end

  def permission_to_edit
    @user = User.find_by! name_lower: params[:id]
    no_permission_redirect! unless @user.can_edit?(current_user)
  end
end

app/views/users/edit.html.slim
= form_for @user, remote: true, html: { id: 'settings_form' } do |f|
  h2 = t('.title')
  = field_set_tag do
    = f.check_box(:show_nsfw, data: { 'body-off': 'hide-nsfw' })
    = f.label(:show_nsfw, t('.show_nsfw'))
  div.status.saving = fa_tag('spinner fa-spin') + t('status.saving')
  div.status.saved = fa_tag('check') + t('status.saved')
  div.status.error = fa_tag('warning') + t('status.error')
= form_for @user, remote: true, html: { id: 'user_profile_form' } do |f|
  h3 = t('.update_profile')
  = f.hidden_field :update_profile, value: 1
  = f.label :email
  = f.text_field :email, class: 'u-full-width', maxlength: attribute_max(User, :email)
  = f.label :profile
  = render 'comments/markdown_help', field: f.text_area(:profile, class: 'u-full-width', placeholder: t('.about_profile'))
  = f.button t('buttons.submit'), class: 'button-primary'
= form_for @user, remote: true, html: { id: 'user_password_form' } do |f|
  h3 = t('.update_password')
  = f.hidden_field :update_password, value: 1
  = f.label :current_password, class: 'required'
  = f.password_field :current_password, class: 'u-full-width'
  = f.label :password, t('.new_password'), class: 'required'
  = f.password_field :password, class: 'u-full-width'
  = f.label :password_confirmation, class: 'required'
  = f.password_field :password_confirmation, class: 'u-full-width'
  = f.button t('buttons.submit'), class: 'button-primary'

app/views/users/new.html.slim
= form_for :session, remote: true, url: sessions_path, html: { id: 'session_form' } do |f|
  h2 = t '.sign_in'
  = f.label :name, class: 'required', maxlength: attribute_max(User, :name)
  = f.text_field :name, class: 'u-full-width'
  = f.label :password, class: 'required'
  = f.password_field :password, class: 'u-full-width'
  = field_set_tag do
    = f.check_box(:remember) + f.label(:remember, t('.remember'))
  = captcha 'sign_in', show_when_risky: true
  = f.button t('.sign_in'), class: 'button-primary'
= form_for :user, remote: true, url: users_path, html: { id: 'user_form' } do |f|
  h2 = t '.register'
  = f.label :name, class: 'required'
  = f.text_field :name, class: 'u-full-width', maxlength: attribute_max(User, :name), placeholder: t('.name_placeholder')
  = f.label :password, class: 'required'
  = f.password_field :password, class: 'u-full-width'
  = f.label :password_confirmation, class: 'required'
  = f.password_field :password_confirmation, class: 'u-full-width'
  = f.label :email
  = f.text_field :email, class: 'u-full-width', maxlength: attribute_max(User, :email), placeholder: t('.email_placeholder')
  = field_set_tag do
    = f.check_box(:remember)
    = f.label(:remember, t('.remember'))
  = captcha 'register'
  = f.button t('.register'), class: 'button-primary'

app/views/users/show.html.slim
h2 = t '.header', user: @user.name
- if @user.can_edit?(current_user)
  = link_to t('users.edit.title'), edit_user_path(params[:id]), class: 'button mr'
- if current_user?(@user)
  = link_to t('users.sign_out'), sign_out_path, method: 'delete', class: 'button'
- unless @user.profile.blank?
  h6 = t('.profile')
  div.markdown = MarkdownParser.markdown_convert @user.profile
h6 = t('.latest_comments')
| Latest comments and links submitted will be shown here.