config/routes.rb
Rails.application.routes.draw do
  scope constraints: { format: :html } do

    resources :sessions, only: [:create, :destroy]
    resources :comments
    resources :links,    only: [:index, :show, :new, :create]
    resources :votes,    only: [:create]
    resources :users

    get "/submit" => "links#new"

    get '/sign_in',  to: 'users#new'
    delete '/sign_out', to: 'sessions#destroy'

    get "/:category/submit" => "links#new"
    get "/:category/:subcategory/submit" => "links#new"
    get "/:category/:subcategory/:slug" => "links#show"
    get "/:category/:subcategory" => "links#index"
    get "/:category" => "links#index"
  end
  root 'links#index'
  get '*unmatched_route', to: 'application#raise_not_found!'
end

app/views/layouts/_sidebar.html.slim
aside
  ul
    - if signed_in?
      li.user
        = link_to fa_tag('user') + content_tag(:span, current_user.name),
          user_path(current_user.name_lower)
        = link_to fa_tag('plus-circle'), '#', class: 'exp'
        ol
          li = link_to t('users.edit.title'), edit_user_path(current_user.name_lower)
          li = link_to t('users.sign_out'), sign_out_path, method: 'delete'
      li.submit = link_to fa_tag('plus') + t('links.new.title'),
        (@category_path.nil? ? '' : @category_path) + '/submit', title: t('links.new.title')
    - else
      li.user
        = link_to fa_tag('user') + content_tag(:span, t('users.new.title')), sign_in_path
    - unless @categories.nil? || @categories[0].nil?
      - for category in @categories[0]
        li
          = link_to fa_tag(category.icon) + category.name.html_safe,
            category.path, title: category.name
          = link_to fa_tag('plus-circle'), '#', class: 'exp'
          - unless @categories[category.id].nil?
            ol
              - for child in @categories[category.id]
                li = link_to child.name, child.path

app/views/layouts/application.html.slim
doctype html
html
  head
    title = title_tag @title
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    script src='https://www.google.com/recaptcha/api.js?onload=load_captchas&render=explicit'
  body class='#{body_classes}'
    /div#main
    header
      h1
        = link_to t(:site_name), root_url
        = mini_title_tag @mini_title, @mini_url, fallback=@title
      a#menu href='#' = fa_tag('bars')
      - if signed_in?
        = link_to fa_tag('user'), user_path(current_user.name_lower), id: 'user',
          data: { 'weight-up': current_user.weight_up, 'weight-down': current_user.weight_down }
      - else
        = link_to fa_tag('user'), sign_in_path, id: 'user'
    / end of header
    = render 'layouts/sidebar'
    div#content
      == alerts
      == yield

app/views/layouts/error.html.slim
div#fatal_error
  h4 A fatal error occurred:
  = content_tag :p, @error